package io.dourl.mqtt.model.message.emoji;


import io.dourl.mqtt.R;
import io.dourl.mqtt.utils.ImSmileUtils;

public class DefaultEmojiconDatas {

    private static String[] emojis = new String[]{
            ImSmileUtils.Expression_1,
            ImSmileUtils.Expression_2,
            ImSmileUtils.Expression_3,
            ImSmileUtils.Expression_4,
            ImSmileUtils.Expression_5,
            ImSmileUtils.Expression_6,
            ImSmileUtils.Expression_7,
            ImSmileUtils.Expression_8,
            ImSmileUtils.Expression_9,
            ImSmileUtils.Expression_10,
            ImSmileUtils.Expression_11,
            ImSmileUtils.Expression_12,
            ImSmileUtils.Expression_13,
            ImSmileUtils.Expression_14,
            ImSmileUtils.Expression_15,
            ImSmileUtils.Expression_16,
            ImSmileUtils.Expression_17,
            ImSmileUtils.Expression_18,
            ImSmileUtils.Expression_19,
            ImSmileUtils.Expression_20,
            ImSmileUtils.Expression_21,
            ImSmileUtils.Expression_22,
            ImSmileUtils.Expression_23,
            ImSmileUtils.Expression_24,
            ImSmileUtils.Expression_25,
            ImSmileUtils.Expression_26,
            ImSmileUtils.Expression_27,
            ImSmileUtils.Expression_28,
            ImSmileUtils.Expression_29,
            ImSmileUtils.Expression_30,
            ImSmileUtils.Expression_31,
            ImSmileUtils.Expression_32,
            ImSmileUtils.Expression_33,
            ImSmileUtils.Expression_34,
            ImSmileUtils.Expression_35,
            ImSmileUtils.Expression_36,
            ImSmileUtils.Expression_37,
            ImSmileUtils.Expression_38,
            ImSmileUtils.Expression_39,
            ImSmileUtils.Expression_40,
            ImSmileUtils.Expression_41,
            ImSmileUtils.Expression_42,
            ImSmileUtils.Expression_43,
            ImSmileUtils.Expression_44,
            ImSmileUtils.Expression_45,
            ImSmileUtils.Expression_46,
            ImSmileUtils.Expression_47,
            ImSmileUtils.Expression_48,
            ImSmileUtils.Expression_49,
            ImSmileUtils.Expression_50,
            ImSmileUtils.Expression_51,
            ImSmileUtils.Expression_52,
            ImSmileUtils.Expression_53,
            ImSmileUtils.Expression_54,
            ImSmileUtils.Expression_55,
            ImSmileUtils.Expression_56,
            ImSmileUtils.Expression_57,
            ImSmileUtils.Expression_58,
            ImSmileUtils.Expression_59,
            ImSmileUtils.Expression_60,
            ImSmileUtils.Expression_61,
            ImSmileUtils.Expression_62,
            ImSmileUtils.Expression_63,
            ImSmileUtils.Expression_64,
            ImSmileUtils.Expression_65,
            ImSmileUtils.Expression_66,
            ImSmileUtils.Expression_67,
            ImSmileUtils.Expression_68,
            ImSmileUtils.Expression_69,
            ImSmileUtils.Expression_70,
            ImSmileUtils.Expression_71,
            ImSmileUtils.Expression_72,
            ImSmileUtils.Expression_73,
            ImSmileUtils.Expression_74,
            ImSmileUtils.Expression_75,
            ImSmileUtils.Expression_76,
            ImSmileUtils.Expression_77,
            ImSmileUtils.Expression_78,
            ImSmileUtils.Expression_79,
            ImSmileUtils.Expression_80,
            ImSmileUtils.Expression_81,
            ImSmileUtils.Expression_82,
            ImSmileUtils.Expression_83,
            ImSmileUtils.Expression_84,
            ImSmileUtils.Expression_85,
            ImSmileUtils.Expression_86,
            ImSmileUtils.Expression_87,
            ImSmileUtils.Expression_88,
            ImSmileUtils.Expression_89,
            ImSmileUtils.Expression_90,
            ImSmileUtils.Expression_91,
            ImSmileUtils.Expression_92,
            ImSmileUtils.Expression_93,
            ImSmileUtils.Expression_94,
            ImSmileUtils.Expression_95,
            ImSmileUtils.Expression_96,
            ImSmileUtils.Expression_97,
            ImSmileUtils.Expression_98,
            ImSmileUtils.Expression_99,
            ImSmileUtils.Expression_100
    };

    private static int[] icons = new int[]{
            R.drawable.ee_1,
            R.drawable.ee_2,
            R.drawable.ee_3,
            R.drawable.ee_4,
            R.drawable.ee_5,
            R.drawable.ee_6,
            R.drawable.ee_7,
            R.drawable.ee_8,
            R.drawable.ee_9,
            R.drawable.ee_10,
            R.drawable.ee_11,
            R.drawable.ee_12,
            R.drawable.ee_13,
            R.drawable.ee_14,
            R.drawable.ee_15,
            R.drawable.ee_16,
            R.drawable.ee_17,
            R.drawable.ee_18,
            R.drawable.ee_19,
            R.drawable.ee_20,
            R.drawable.ee_21,
            R.drawable.ee_22,
            R.drawable.ee_23,
            R.drawable.ee_24,
            R.drawable.ee_25,
            R.drawable.ee_26,
            R.drawable.ee_27,
            R.drawable.ee_28,
            R.drawable.ee_29,
            R.drawable.ee_30,
            R.drawable.ee_31,
            R.drawable.ee_32,
            R.drawable.ee_33,
            R.drawable.ee_34,
            R.drawable.ee_35,
            R.drawable.ee_36,
            R.drawable.ee_37,
            R.drawable.ee_38,
            R.drawable.ee_39,
            R.drawable.ee_40,
            R.drawable.ee_41,
            R.drawable.ee_42,
            R.drawable.ee_43,
            R.drawable.ee_44,
            R.drawable.ee_45,
            R.drawable.ee_46,
            R.drawable.ee_47,
            R.drawable.ee_48,
            R.drawable.ee_49,
            R.drawable.ee_50,
            R.drawable.ee_51,
            R.drawable.ee_52,
            R.drawable.ee_53,
            R.drawable.ee_54,
            R.drawable.ee_55,
            R.drawable.ee_56,
            R.drawable.ee_57,
            R.drawable.ee_58,
            R.drawable.ee_59,
            R.drawable.ee_60,
            R.drawable.ee_61,
            R.drawable.ee_62,
            R.drawable.ee_63,
            R.drawable.ee_64,
            R.drawable.ee_65,
            R.drawable.ee_66,
            R.drawable.ee_67,
            R.drawable.ee_68,
            R.drawable.ee_69,
            R.drawable.ee_70,
            R.drawable.ee_71,
            R.drawable.ee_72,
            R.drawable.ee_73,
            R.drawable.ee_74,
            R.drawable.ee_75,
            R.drawable.ee_76,
            R.drawable.ee_77,
            R.drawable.ee_78,
            R.drawable.ee_79,
            R.drawable.ee_80,
            R.drawable.ee_81,
            R.drawable.ee_82,
            R.drawable.ee_83,
            R.drawable.ee_84,
            R.drawable.ee_85,
            R.drawable.ee_86,
            R.drawable.ee_87,
            R.drawable.ee_88,
            R.drawable.ee_89,
            R.drawable.ee_90,
            R.drawable.ee_91,
            R.drawable.ee_92,
            R.drawable.ee_93,
            R.drawable.ee_94,
            R.drawable.ee_95,
            R.drawable.ee_96,
            R.drawable.ee_97,
            R.drawable.ee_98,
            R.drawable.ee_99,
            R.drawable.ee_100,
    };


    private static final Emojicon[] DATA = createData();

    private static Emojicon[] createData() {
        Emojicon[] datas = new Emojicon[icons.length];
        for (int i = 0; i < icons.length; i++) {
            datas[i] = new Emojicon(icons[i], emojis[i], Emojicon.Type.NORMAL);
        }
        return datas;
    }

    public static Emojicon[] getData() {
        return DATA;
    }
}
